targets:
  $default:
    builders:
      drift_dev:
        enabled: true
        options:
          generate_connect_constructor: false
          scoped_dart_components: true
      freezed:
        enabled: true
      json_serializable:
        enabled: true
        options:
          explicit_to_json: true
          include_if_null: false
      riverpod_generator:
        enabled: true
